### ISSUE TITLE
Change Footer

### ISSUE THREAD

**Issue by aditi10701** [Kirankp25/TODO#16]
Footer style can be changed and more details about the creator can be added.
Kindly assign me the same. I can work in it.

**Comment by Kirankp25** [comment]
ok, good to go but before pr put your changes here by taking a screenshot of the new changes

**Comment by aditi10701** [comment]
The updated footer looks like this.
Should I push the changes?
![image](https://user-images.githubusercontent.com/98349669/193499266-98064222-2043-4d27-8e6a-757ecae11230.png)

**Comment by Kirankp25** [comment]
Good 👍 job but social media icons are not visible here

**Comment by Kirankp25** [comment]
are you working on it  or not

**Comment by aditi10701** [comment]
Yes I am working on it. 
Will push the changes asap.

**Comment by Kirankp25** [comment]
ok

**Comment by aditi10701** [comment]
The footer is completely added with active social media icons.
Can I push the changes?
![Uploading image.png…]()

**Comment by aditi10701** [comment]
![image](https://user-images.githubusercontent.com/98349669/194690896-3cd9684c-982f-458f-ab17-d112e70ed5da.png)

**Comment by Kirankp25** [comment]
take a current update of our site and if you want make some changes so minimize the space between social media icons and make it center align of contact us section

**Comment by Kirankp25** [comment]
Already updated...
