### ISSUE TITLE
To create button for dark and white mode

### ISSUE THREAD

**Issue by Kirankp25** [Kirankp25/TODO#22]
If anyone wants to work on it, feel free to contribute here

**Comment by himanshukandpal-28** [comment]
Hey Kiran, can I work on this?

**Comment by Kirankp25** [comment]
> If anyone wants to work on it, feel free to contribute here

sure go ahead

**Comment by Kirankp25** [comment]
send current updates here

**Comment by Kirankp25** [comment]
issue updated
