### ISSUE TITLE
can i redesign UI?

### ISSUE THREAD

**Issue by gurupawar** [Kirankp25/TODO#23]

**Comment by gurupawar** [comment]
want to redesign whole ui

**Comment by Kirankp25** [comment]
which changes do you want to make here ...?

**Comment by gurupawar** [comment]
want to redesing whole ui.. it looks very dull so thinking to desing using bootstrap or tailwindCss

**Comment by Kirankp25** [comment]
> want to redesing whole ui.. it looks very dull so thinking to desing using bootstrap or tailwindCss

👍

**Comment by Kirankp25** [comment]
hello @gurupawar are you working on this issue or not

**Comment by gurupawar** [comment]
no
