### ISSUE TITLE
I want to add Current day Section.

### ISSUE THREAD

**Issue by SxxAq** [Kirankp25/TODO#27]
which will be heading like this
![image](https://user-images.githubusercontent.com/98530202/193888804-132c4661-6511-4304-a5f8-d9da568d64e1.png)

**Comment by Kirankp25** [comment]
where it will visible

**Comment by SxxAq** [comment]
Top of the Task like this
![image](https://user-images.githubusercontent.com/98530202/194047452-c8462a4e-360a-4d84-9726-5faca5671393.png)

**Comment by Kirankp25** [comment]
not required for this static site
