### ISSUE TITLE
UI : few changes like footer, social media icons and more.

### ISSUE THREAD

**Issue by zabihhaqqani** [Kirankp25/TODO#30]
## changes that I propose

- remove the extra footer
![asdf](https://user-images.githubusercontent.com/53895282/194608376-96fb251f-e854-45c8-8e9f-12e92262f87b.PNG)
- the visibility is bad in the inputs
![a](https://user-images.githubusercontent.com/53895282/194608872-36e9a478-6ca2-45e8-ae3d-74a9e0690eb7.PNG)
- add proper social media icons from font awesome.
![footer](https://user-images.githubusercontent.com/53895282/194609180-ce877cd1-b378-477f-8b38-5095053ae148.PNG)
- use a better font like Poppins, dm sans, or Roboto.

**Comment by Kirankp25** [comment]
go ahead

**Comment by zabihhaqqani** [comment]
Thanks on it!

**Comment by Kirankp25** [comment]
It's alraedy updated ,so no need to make pr

**Comment by zabihhaqqani** [comment]
Sure no problem
