### ISSUE TITLE
'You don't have any task to do.' shows even if you have tasks to do.

### ISSUE THREAD

**Issue by ann0nip** [Kirankp25/TODO#32]
<img width="1439" alt="Screen Shot 2022-10-07 at 14 33 04" src="https://user-images.githubusercontent.com/2248100/194616499-2b05812f-a3b4-4ce1-a42b-099cee51d64b.png">

How to reproduce the issue:
- Create a task.
- Reload the page.
- The message shows even when you have incomplete tasks.

I can work on that issue.

**Comment by Kirankp25** [comment]
go ahead
