### ISSUE TITLE
Add CSS

### ISSUE THREAD

**Issue by Architgupta001** [Kirankp25/TODO#5]
I want to add CSS, to make it look more good. Please assign this task to me

**Comment by Kirankp25** [comment]
Go ahead

**Comment by Candy505** [comment]
@Kirankp25 Hey ! I would like to make some changes, a more user-friendly interface/design.

**Comment by Kirankp25** [comment]
@Candy505 which changes you want to do

**Comment by Candy505** [comment]
![Screenshot (292)](https://user-images.githubusercontent.com/87769883/193469850-bea9e70c-05d7-4175-bb95-55f009928b17.png)

@Kirankp25 How does this look to you? This is mostly what I would like to modify.

**Comment by Kirankp25** [comment]
at add button it should be at the center

**Comment by Candy505** [comment]
> at add button it should be at the center

Yep, I initially tried but could not achieve the result. I'll look into it.

**Comment by Kirankp25** [comment]
> > at add button it should be at the center
> 
> Yep, I initially tried but could not achieve the result. I'll look into it.

ok work on it and I think the green background is not suitable

**Comment by Candy505** [comment]
I would appreciate few suggestions on the color part.... how do you want it ? any rough idea if you want dark/light shades ? @Kirankp25

**Comment by Kirankp25** [comment]
> I would appreciate few suggestions on the color part.... how do you want it ? any rough idea if you want dark/light shades ? @Kirankp25

background should be like a glassy effect in black  color shades

**Comment by Candy505** [comment]
![Screenshot (299)](https://user-images.githubusercontent.com/87769883/193613893-4cac945e-0c79-483f-b9fe-0385fce51caf.png)

@Kirankp25 Hey ! take a look , I made changes. If it's suitable kindly merge.

**Comment by Kirankp25** [comment]
@Candy505  kindly check the current update

**Comment by Kirankp25** [comment]
send current updates
