### ISSUE TITLE
Change Font style of MyTodo

### ISSUE THREAD

**Issue by Pritam0077** [Kirankp25/TODO#7]
I want change the fontstyle of MyTodo header pls assign it to me

**Comment by Kirankp25** [comment]
go ahead @Pritam0077 and before pr put screenshot of new changes

**Comment by Pritam0077** [comment]
OK

**Comment by Pritam0077** [comment]
<img width="496" alt="image" src="https://user-images.githubusercontent.com/89348093/193439338-8ed9149c-d04d-456a-a637-d3d24a6e3b46.png">
check it out

**Comment by Kirankp25** [comment]
the second one looks good

**Comment by Pritam0077** [comment]
ok
